### ISSUE TITLE
censys API rate limit?

### ISSUE THREAD

**Issue by fishouttah20** [tomsteele/blacksheepwall#15]
When doing a censys scan against a large file of domains, the first few succeed and then I see a long list of "Request returned non 200 status code. (with debugging enabled). I'm wondering if the default settings are overloading the rate limit the default free account provides?

**Comment by tomsteele** [comment]
@mattburch You have time to dig into this one?

**Comment by fishouttah20** [comment]
From my free account page:

Rate Limits
Censys rate limits are enforced using token buckets. Below are the token bucket rates associated with your account.

query 0.0 tokens/second (0.0 per 5 minute bucket)
search 0.2 tokens/second (60.0 per 5 minute bucket)
api 0.4 tokens/second (120.0 per 5 minute bucket)
