### ISSUE TITLE
Use new azure search API

### ISSUE THREAD

**Issue by tomsteele** [tomsteele/blacksheepwall#19]

**Comment by b00stfr3ak** [comment]
Documentation: https://www.microsoft.com/cognitive-services/en-us/bing-web-search-api/documentation

Examples: https://dev.cognitive.microsoft.com/docs/services/56b43eeccf5ff8098cef3807/operations/56b4447dcf5ff8098cef380d

API console: https://dev.cognitive.microsoft.com/docs/services/56b43eeccf5ff8098cef3807/operations/56b4447dcf5ff8098cef380d/console

Curl Command:  curl -v "https://api.cognitive.microsoft.com/bing/v5.0/search?q=XXX.XXX.XXX.XXX&count=10&offset=0&mkt=en-us&safesearch=Off" -H "Ocp-Apim-Subscription-Key: XXXXXXXXXXXXXX"
