### ISSUE TITLE
Program crash on Windows 10

### ISSUE THREAD

**Issue by jmhickman** [tomsteele/blacksheepwall#20]
Unless I'm mistaken, these compiled binaries should work without Go installed on the system? 

If so, the latest version and the next oldest, at least, do not. They crash with the following with no arguments, or just an IP address argument.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x30 pc=0x402aba]

goroutine 1 [running]:
panic(0x7214c0, 0xc04200a090)
        /usr/local/opt/go/libexec/src/runtime/panic.go:500 +0x1af
main.main()
        /Users/t/Code/go/src/github.com/tomsteele/blacksheepwall/main.go:300 +0xc7a

```

I tried running in an admin shell, just in case, but that didn't make any difference. 
OS is Windows 10 1607 14393.576 64 bit

**Comment by tomsteele** [comment]
I have a fix for this that I will push. It's a stdin thing.

**Comment by tomsteele** [comment]
Thanks for letting me know about this. I tested newest build v3.0.6 and it's working great.
