### ISSUE TITLE
Common Crawl is running without being called.

### ISSUE THREAD

**Issue by assimilat** [tomsteele/blacksheepwall#21]
Between commits 6ded4f6 and 6095a91
`./blacksheepwall -server 192.168.1.1 -reverse 192.168.1.0/24`
returns
`2017/04/12 19:10:22 Common Crawl requires domain set with -domain`
It works as expected with builds from before 96b9402.

**Comment by ilyaglow** [comment]
The fix is dead easy, you should go to [main.go](https://github.com/tomsteele/blacksheepwall/blob/master/main.go#L336)

And set `*flCommonCrawl ==`
```
	if *flCommonCrawl == "" && *flDomain == "" {
```

to `*flCommonCrawl !=`
```
	if *flCommonCrawl != "" && *flDomain == "" {
```
