### ISSUE TITLE
Error in third party repo

### ISSUE THREAD

**Issue by binary1985** [tomsteele/blacksheepwall#28]
Looks like the dependency miekg/dns has changed and causes this build to fail.

$ go get github.com/tomsteele/blacksheepwall
# github.com/miekg/dns
../../../Tools/Programming/go/src/github.com/miekg/dns/client.go:489: undefined: time.Until
../../../Tools/Programming/go/src/github.com/miekg/dns/dnssec_keyscan.go:295: undefined: strings.Builder
../../../Tools/Programming/go/src/github.com/miekg/dns/msg_helpers.go:144: base32.HexEncoding.WithPadding undefined (type *base32.Encoding has no field or method WithPadding)
../../../Tools/Programming/go/src/github.com/miekg/dns/msg_helpers.go:144: undefined: base32.NoPadding
../../../Tools/Programming/go/src/github.com/miekg/dns/msg_helpers.go:270: undefined: strings.Builder
../../../Tools/Programming/go/src/github.com/miekg/dns/serve_mux.go:43: undefined: strings.Builder
../../../Tools/Programming/go/src/github.com/miekg/dns/types.go:422: undefined: strings.Builder
../../../Tools/Programming/go/src/github.com/miekg/dns/types.go:495: undefined: strings.Builder
../../../Tools/Programming/go/src/github.com/miekg/dns/types.go:505: undefined: strings.Builder
../../../Tools/Programming/go/src/github.com/miekg/dns/types.go:517: undefined: strings.Builder
../../../Tools/Programming/go/src/github.com/miekg/dns/types.go:422: too many errors

**Comment by ilyaglow** [comment]
Seems like you have an old version of Go installed. You can check it with `go version`.

The `strings.Builder` was introduced in `1.10` version. A most recent version of Go is  `1.12.1`.
